# Generated by Django 4.0.5 on 2022-07-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del producto', max_length=20, verbose_name='Nombre del producto')),
                ('description', models.CharField(help_text='Descripción', max_length=100, verbose_name='Descripción')),
                ('price', models.PositiveIntegerField(null=True, verbose_name='Precio')),
                ('image', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
            ],
            options={
                'ordering': ['-price'],
            },
        ),
    ]
